### ISSUE TITLE
Error: Microsoft Visual C++ is required

### ISSUE THREAD

**Issue by Sinsst** [rtavenar/tslearn#102]
Hi,

While trying to install tslearn, I encountered the above error. Obviously, I'm trying to dodge installing Microsoft Visual C++ which is 5GB and was wondering if anyone figured out which binaries are needed to bypass this? I think it's Cython related, but I've trying installing the binaries and 'requirement is already satisfied'. Actual error below:

`  ERROR: Complete output from command 'D:\Anaconda3\envs\deep-learning\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-yy1klzjw\\tslearn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\name\AppData\Local\Temp\pip-wheel-tcf14c5a' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\tslearn
  copying tslearn\barycenters.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\clustering.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\datasets.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\generators.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\metrics.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\neighbors.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\piecewise.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\preprocessing.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\shapelets.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\svm.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\utils.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\__init__.py -> build\lib.win-amd64-3.7\tslearn
  creating build\lib.win-amd64-3.7\tslearn\.cached_datasets
  copying tslearn\.cached_datasets\Trace.npz -> build\lib.win-amd64-3.7\tslearn\.cached_datasets
  running build_ext
  skipping 'tslearn\cydtw.c' Cython extension (up-to-date)
  building 'tslearn.cydtw' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for tslearn`

**Comment by GillesVandewiele** [comment]
I think you will have to install the Visual C++ compiler unfortunately.

On the other hand, the Ubuntu iso file is only 2 GB instead of 5 GB and you won't ever have this stupid problems again ;)

**Comment by rtavenar** [comment]
C++ build tools are necessary to use Cython, which is a hard dependency for `tslearn`, as stated there: #90 .
