### ISSUE TITLE
GAK kMeans Question

### ISSUE THREAD

**Issue by Simon0494** [rtavenar/tslearn#107]
Hey Romain, 

i have a question related to GAK k-means clustering.
Its not an actual issue, but i was wondersing how the centroids of k-means are calclated in this implementation using GAK? 
If the centers are the most representative time series, wouldnt it have to be called k-medoids instead of k-means?

Thanks :)

**Comment by rtavenar** [comment]
Are you talking about Global Alignment Kernel kmeans? If so, there are no centroids available, only assignment of each time series to a cluster.

**Comment by Simon0494** [comment]
Hello, thanks for your answer! Yes, but to assign time series towards a cluster, the cluster somehow needs to be represented by a time series, or am i wrong? I thought Global Alignment Kernel kmeans is just kmeans appield with a GAK kernel. In kmeans there are usually some initial time series are chosen as center of some initial clusters, then time series are assigned and a new center of the resulting clusters is calculated. How is this new center chosen? is it the average of the time series?

**Comment by rtavenar** [comment]
In kernel kmeans, there is no explicit barycenter, contrary to kmeans.
If you need such explicit barycenter, I would suggest you use kmeans with softdtw as the metric. Softdtw is closely related to gak, you could read the associated paper if you want more information.

**Comment by Simon0494** [comment]
Oh okey, thank you, i did not notice that... thats probably why i missed it because i only knew about the standard kmeans and thought kernels are just some sort of similarity measure exchange. I was primarily searching in the kernel kmeans for single center update step in the paper. I guess i will have to read it more elaboratively. Thank you!
