### ISSUE TITLE
Saving multivariate time series in text files

### ISSUE THREAD

**Issue by fahadalisarwar1** [rtavenar/tslearn#109]
the save_timeseries  method only support saving for univariate time series as per my understanding, it would be nice if we could save multivariate timeseries as well. The load_timeseries works fine on multivariate time series.

**Comment by yichangwang** [comment]
Hi @fahadalisarwar1 

I have two functions to save and load multivariate time series. Maybe it's useful for you.

```
def save_multi(X_train):
    header = ','.join(map(str, X_train.shape))
    np.savetxt('test.txt', X_train.reshape(-1, X_train.shape[-1]),
               header=header,
               delimiter=',')


def load_multi():
    with open('test.txt', 'r') as f:
        shape = map(int, f.readline()[1:].split(','))
        # load txt as (nb_example, channels, length)
        # columns = range(tuple(shape)[2])
        temp = np.loadtxt(f, delimiter=',').reshape(tuple(shape))
        # reshpe to (nb_example, length, channels)
        xx = temp.transpose(0, 2, 1)
    return xx


if __name__ == "__main__":
    X_train, y_train, X_test, y_test = UCR_UEA_datasets().load_dataset("PenDigits")
    print(X_train.shape)
    save_multi(X_train)
    x = load_multi()
    print(x.shape)
```

**Comment by fahadalisarwar1** [comment]
Hi, thanks for your reply. np.savetext works fine when the series of different variables are of same length. I dont think it works with series of variable length.

**Comment by rtavenar** [comment]
Hi @fahadalisarwar1 

First, thanks for your interest in tslearn ! 

Have you tried saving multivariate time series to disk using save_timeseries_txt ? Could you provide a failing example ? Does it fail only for variable length time series ? 

Thanks for your help.

**Comment by fahadalisarwar1** [comment]
hi, can you please provide an example on how the variables should be input to the save_timeseries_txt() method. 
```
import numpy as np
from tslearn.utils import save_timeseries_txt, to_time_series_dataset, to_time_series, load_timeseries_txt

np.random.seed(0)
f1 = np.array(np.random.random(8)).reshape((2, 4))
np.random.seed(1)
f2 = np.array(np.random.random(8)).reshape((2, 4))
np.random.seed(3)
f3 = np.array(np.random.random(8)).reshape((2, 4))


save_timeseries_txt('test.txt', [f1, f2, f3])
loaded_file = load_timeseries_txt('test.txt')
```
i have three 2 time series with 3 variables and each series with 4 time stamps. I dont know how to save it in the required format. Is this a correct method to input to data to the neighbor classifier?

**Comment by rtavenar** [comment]
I just added an example in the docs of this function for variable-length time series. The docs should build in a few minutes

**Comment by fahadalisarwar1** [comment]
Thank you!
