### ISSUE TITLE
Example code fails

### ISSUE THREAD

**Issue by fonnesbeck** [rtavenar/tslearn#11]
I've tried a couple of the examples in the docs, but none of them appear to work. It looks like the data shapes are different than are expected in the examples. For instance, in the DTW example:

```python
sz = X_train.shape[1]
```

results in `IndexError: tuple index out of range`. Similarly in the kernel k-means example, `dataset_scaled[0, :, 0]` yields an index error suggesting that there are only 2 dimensions. 

Running from today's master branch on Python 3.6.

**Comment by rtavenar** [comment]
This is my fault, I commited some buggy code today and did not have time to fix the bugs. Until I do, you can use the pypi version that correspond to the last working version.
Yo do do, just do 

pip install tslearn

Sorry for the inconvenience...

**Comment by fonnesbeck** [comment]
Great, that's what I've done .. thanks.

**Comment by rtavenar** [comment]
Now the bug should be fixed from commit [731bd4b](https://github.com/rtavenar/tslearn/commit/731bd4bff030d5b93034b0954bbb6fb4dbd84d32).

**Comment by fonnesbeck** [comment]
Thanks!
