### ISSUE TITLE
TimeSeriesKMeans with DTW consume too much time

### ISSUE THREAD

**Issue by thusithathilina** [rtavenar/tslearn#121]
I'm trying to use TimeSeriesKMeans with both Ecul and DTW for a dataset which consists about 300000 time-series (each is having 48 values. The issue is when I set the metric to DTW, it takes more than 5 days to run. With Eculeadean I can run it just in few hours. Does TimeSeriesKMeans use underlying TensorFlow GPU capabilities? Or is it always running on a single core? If so, is there any way I can reduce the time?

**Comment by rtavenar** [comment]
Hi @thusithathilina 

Sorry for the late answer.
We are at the moment working on a faster implementation of DTW (available by default in the `dev` branch of this repository), so I hope this could help with your issue.
We are not using any GPU capability at the moment (and DTW is not an algorithm that is very easy to parallelize, though ground cost matrix could be computed in parallel, definitely).

Hope this answers your question.

Best regards,
Romain

**Comment by bujianbusan** [comment]
so, i donot run dtw path by GPU?  then ,the time for exe is so long, do you have some other solution ?
