### ISSUE TITLE
Progress/status

### ISSUE THREAD

**Issue by choltz95** [rtavenar/tslearn#127]
For my application, I have a dataset of ~30k 6-dimensional sequences of max-length 300. I want to tune the maximum length to make the runtime of computing DTW/GAK similarity matrices feasible, but the getting the expected runtime is not clear. Is it possible to have a verbosity flag or progress bar for these functions? 

A couple questions:

1. Would it be reasonable to wrap the outer for loop in [cdist_dtw ](https://github.com/rtavenar/tslearn/blob/master/tslearn/cydtw.pyx#L152) with a tqdm statement? 
2. Would this reduce runtime by a significant amount?
3. Is $ python setup.py install sufficient to build?

**Comment by rtavenar** [comment]
Hi @choltz95 

I am not sure adding an external dependency for that would be a great idea, sorry.

As I said on another issue, dtw should be much faster starting from version 0.2 (currently available on dev branch).

Hope this helps

**Comment by choltz95** [comment]
I was just asking wrt to a local build. It works fine.
