### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by daltonfury42** [rtavenar/tslearn#132]
Looks like setup.py is importing cython, which is a dependency:

> Collecting tslearn
>   Downloading https://files.pythonhosted.org/packages/af/f9/7225f4b1e7ba482b10b544cecf50a0a92bfbbde4ec30fdce824a867ad9ab/tslearn-0.1.29.tar.gz (587kB)
>     100% |████████████████████████████████| 593kB 766kB/s 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-4bo4i_6k/tslearn/setup.py", line 5, in <module>
>         from Cython.Distutils import build_ext as _build_ext
>     ModuleNotFoundError: No module named 'Cython'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4bo4i_6k/tslearn/
>

**Comment by GillesVandewiele** [comment]
This can indeed happen sometimes... Could you try `pip install Cython` first and see if it works?

**Comment by daltonfury42** [comment]
There is a way around this, though: https://github.com/LeeKamentsky/python-javabridge/pull/131/files#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by rtavenar** [comment]
`cython` and `numpy` are now declared as build time requirements for PyPI and github-based installs (basically source-based installs) in the docs.

`conda` install should make things easier for those who can use it.

And #150 will be used to advance on the question of releasing wheels for a wide range of platforms on PyPI.
