### ISSUE TITLE
pip install fail --CANNOT Building wheels for Tslearn Windows 

### ISSUE THREAD

**Issue by mengxibai** [rtavenar/tslearn#136]
I had visual studio community 2019 on windows and setted environment variable for cl.exe. But there is still an exist error 2 for cl.exe. Already had CYTHON.
Please help.

Building wheel for tslearn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\NAMEi\desktop\python 3.7.2\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NAME\\AppData\\Local\\Temp\\pip-install-26p12gsl\\tslearn\\setup.py'"'"'; __file__='"'"'C:\\Users\\NAME\\AppData\\Local\\Temp\\pip-install-26p12gsl\\tslearn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\MENGXI~2\AppData\Local\Temp\pip-wheel-klv7l5cn' --python-tag cp37
       cwd: C:\Users\NMAE\AppData\Local\Temp\pip-install-26p12gsl\tslearn\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\tslearn
  copying tslearn\barycenters.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\clustering.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\datasets.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\generators.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\metrics.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\neighbors.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\piecewise.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\preprocessing.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\shapelets.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\svm.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\utils.py -> build\lib.win-amd64-3.7\tslearn
  copying tslearn\__init__.py -> build\lib.win-amd64-3.7\tslearn
  creating build\lib.win-amd64-3.7\tslearn\.cached_datasets
  copying tslearn\.cached_datasets\Trace.npz -> build\lib.win-amd64-3.7\tslearn\.cached_datasets
  running build_ext
  skipping 'tslearn\cydtw.c' Cython extension (up-to-date)
  building 'tslearn.cydtw' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\tslearn
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-Ic:\usersNAME\desktop\python 3.7.2\lib\site-packages\numpy\core\include" "-Ic:\users\NAME\desktop\python 3.7.2\lib\site-packages\numpy\core\include" "-Ic:\users\NAME\desktop\python 3.7.2\include" "-Ic:\users\mengxi bai\desktop\python 3.7.2\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" /Tctslearn\cydtw.c /Fobuild\temp.win-amd64-3.7\Release\tslearn\cydtw.obj
  cydtw.c
  c:\users\NAME\desktop\python 3.7.2\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for tslearn

**Comment by mengxibai** [comment]
SOLVED

**Comment by BrunoStint** [comment]
> SOLVED

how did you solve it? having a similar issue.

**Comment by loubnabnl** [comment]
I had the same error and I tried installing gcc and it worked, on linux RedHat
`sudo dnf install gcc`
