### ISSUE TITLE
Feature Request: Adjustable start point for sDTW path calculation

### ISSUE THREAD

**Issue by AKuederle** [rtavenar/tslearn#137]
With the new implementation of  sDTW, the cost matrix is now calculated first (`njit_accumulated_matrix_subsequence`) and in a second step the path is calculated (`_return_path_subsequence`).

During the path calculation the minimum of the last row (i.e. the best match) is used as starting point. However, there are applications, where not only the best possible path, but the position of potential matches are of interest (e.g. template matching applications). For these cases it would be awesome to be able to specify the starting point of the path calculation:

```
@njit()
def _return_path_subsequence(acc_cost_mat, start_index):
    ...
```

This would move calculation of the argmin to `dtw_subsequence_path`, which would then pass the result as argument to `_return_path_subsequence`.

I would be open to create a small pull request for this feature. In this context I would also propose to make `_return_path_subsequence` public API (i.e. removing the underscore and documenting it).

**Comment by rtavenar** [comment]
Dear @AKuederle 

First, thanks for your interest and the kind words you wrote about `tslearn` :)

Then, I understand that such a feature can be useful, but I guess it has applications in very limited cases. Could you elaborate on typical settings in which you would want to do that instead of, for example `dtw(s1, s2[:start_index])` ?

**Comment by AKuederle** [comment]
Thank you for your fast response!

DTW or rather sDTW is widely used as a template matching algorithm in some fields. For example to find the timepoints of all steps in a movement signal or of all words in a speech signal. In these applications, you would produce a template for the part of the signal you are searching for (e.g. a single step), then calculate the accumulated cost matrix between you long signal and your template. Because you expect multiple occurrences of your template in the signal, the last row of you cost matrix will have local minima (at the specific positions, where your template would match well). You would then extract these matches using some sort of local minima algorithms and then calculate the warping path starting from each of the matches you found.
To give you an example here is a paper using this method to extract strides from IMU signals: [Barth2013](https://ieeexplore.ieee.org/document/6611104).

Because the goal is to find multiple matches, `dtw(s1, s2[:start_index])` would recalculate the cost matrix multiple times, which is not necessary. What I have in mind would something like this:

```python
from tslearn import metrics
cost_mat = metrics.njit_accumulated_matrix_subsequence(subseq, longseq)
matches = find_local_minima(cost_mat[-1, :])  # find_local_minima will depend on the application
for m in matches:
     path = _return_path_subsequence(acc_cost_mat, m)
     ...  # Do something with the path
```

**Comment by AKuederle** [comment]
I added a small pull request to show the amount of changes that would be required.

**Comment by rtavenar** [comment]
OK, if you don't mind, I will try to think about it until tomorrow or next monday and then make my mind about that feature and let you know.

**Comment by AKuederle** [comment]
Of course! Thank you for considering the feature

**Comment by rtavenar** [comment]
Hi @AKuederle 

I thought about this a bit, and I think this could be incorporated in `tslearn` if this is sufficiently documented (ideally with an example in the gallery of such a use case). So if you could include that in your PR #138, it would be great.

**Comment by rtavenar** [comment]
Now available in `dev` branch (will appear in tslearn 0.3) thanks to the great work by @AKuederle !

**Comment by AKuederle** [comment]
Thank you for being so responsive and open to the new feature! This means I can directly use your library now for my current project instead of maintaining some awkward fork of it :)
