### ISSUE TITLE
Multi dimension DTW - dependent vs. independent DTW 

### ISSUE THREAD

**Issue by JonathanTaws** [rtavenar/tslearn#142]
Hi, 

Thanks for this great API to work with timeseries! After reading https://github.com/rtavenar/tslearn/issues/98, I'm not sure I understand how the implementation in tslearn of DTW works across multiple dimensions. The link referenced in the issue to the Cython implementation has moved, so I was not able to exactly pinpoint the line of code. 

Is there also a way to choose between the 2 approaches commonly used to deal with multidimensions (cf. https://www.cs.ucr.edu/~eamonn/Multi-Dimensional_DTW_Journal.pdf), namely the independent version (freedom wrap across all dimensions, simply summing DTW), and the dependent version (cumulative squared euclidean distance across all dimensions)  ? 

Hope I was clear enough, looking forward to your answer.

**Comment by rtavenar** [comment]
Dear @JonathanTaws 

Thanks for your interest in tslearn. 

I thought that the formula used for multidimensional DTW was provided, but it is not. I will change this asap.

To anwer your question: we use the dependent version (and the independent should not be difficult to implement for anyone interested as the sum of tslearn's DTW along each dimension).

**Comment by rtavenar** [comment]
OK, this is now fixed in the docs (cf https://tslearn.readthedocs.io/en/latest/gen_modules/metrics/tslearn.metrics.dtw.html#tslearn.metrics.dtw you may have to refresh several times for the correct formulas with a norm instead of parentheses appears), so I close this thread.

**Comment by JonathanTaws** [comment]
Thanks for the quick answer, this is really helpful! Just curious: is the dependent version being used here as it's more useful/popular in the community? The adaptive approach proposed in the paper of mixing dependent and independent DTW seemed really compelling.

**Comment by rtavenar** [comment]
The thing is: I can understand DTW as the Euclidean distance between re-aligned time series, and this is exactly what the "dependent" version is doing. The independent one does not have such a straight-forward interpretation, but once again, it should not be too difficult to code through calls to `tslearn`'s DTW.
