### ISSUE TITLE
Normalization of Time Series

### ISSUE THREAD

**Issue by vikram-gupta** [rtavenar/tslearn#15]
Hi @rtavenar,

1) Does the DTW distance calculation routine normalizes the time series before calculating distances or the user has to pass pre-normalized sequences.

2) The DTW distance calculation routine seems to accept sequences of different lengths which makes sense as it warps the sequences. However, I am wondering if this routine also does subsequence search? By subsequence search, I am expecting the algorithm to find the most optimum starting point and find the warp path and distance from it.

Thanks

**Comment by rtavenar** [comment]
Hi,

1. No normalization is performed before DTW computation. You can have a look at [the preprocessing module](http://tslearn.readthedocs.io/en/latest/gen_modules/tslearn.preprocessing.html#module-tslearn.preprocessing) to see if the kind of normalization you would expect is implemented in it or not.
2. At the moment, the subsequence search variant of DTW you are mentioning is not  implemented in tslearn. Hence, I add a "new feature" label to the Issue for this part of your question.

Best,
Romain

**Comment by vikram-gupta** [comment]
Thanks @rtavenar !

**Comment by unnamedplay-r** [comment]
It would be good to make a _'search'_ module in tslearn for this routine. We should also consider adding in an online z-normalization routine for streaming sequences. I might make another issue for this.

**Comment by rtavenar** [comment]
Hi @vikram-gupta 

I have added a `dtw_subsequence_path` function to the metrics module: https://github.com/rtavenar/tslearn/blob/master/tslearn/metrics.py#L130

Unfortunately, at the moment, we seem to experience some bugs with ReadTheDocs that prevent from a proper generation of the corresponding doc, but you should be able to use the function however (cf the docstring for an example of how to call the function). This is available from v.0.1.13.

Let me know if this suits you.

Best,
Romain

**Comment by rtavenar** [comment]
I guess no news means good news (as we say in french).

The added function is now in the docs [here](http://tslearn.readthedocs.io/en/latest/gen_modules/metrics/tslearn.metrics.dtw_subsequence_path.html).
Closing this.

**Comment by vikram-gupta** [comment]
Thanks a ton @rtavenar for this enhancement :) And any help is a good help. 

I got caught up with some other project so will give it a try when I am back on this.

Thanks again ! This is a great repo.
