### ISSUE TITLE
Multivariate dtw input format

### ISSUE THREAD

**Issue by Duthopi** [rtavenar/tslearn#157]
Hi, many thanks for this toolkit!
I am trying to get the multivariate DTW to work, but cannot find documentation on the expected format, apologies if this is a basic question.

For example, I am measuring 15 points in 2D that move with time and I want to match them to particular motions in a database. So I am comparing one series of e.g. 20 time-steps of dimension (15, 2) each, with a reference series of e.g. 30 time-steps of the same dimension.
If I try a sample case with random numbers like so:

`metrics.dtw(np.random.rand(20, 15, 2), np.random.rand(30, 15, 2))`

I get an error, which I think is due to the format of my input data:

`numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)`

Would you mind clarifying the expected input for multivariate time series analysis?
Thanks

**Comment by GillesVandewiele** [comment]
So if I am understanding right, you are measuring a X and Y coordinate of 15 things over time? The right format would be (n_samples, n_timesteps, n_dimensions).

Also, dtw is a function that calculates the distance between two timeseries. To calculate the distances between timeseries in a collection `A` and a collection `B` in order to produce a `|A| x |B|` distance matrix, you have to use `cdist_dtw`.

This is a working example:
```python3
>>> import numpy as np
>>> from tslearn.metrics import cdist_dtw
>>> A = np.random.rand(15, 20, 2)
>>> B = np.random.rand(15, 30, 2)
>>> cdist_dtw(X, Y).shape
(15, 15)
```

**Comment by Duthopi** [comment]
Thanks a lot, this is indeed my desired input format.
However I am trying to obtain a single score describing how close the motion of these 15 points is to a reference movement of them, yet `cdist_dtw` returns a matrix instead of a single score like in `dtw`.
Does that imply I should use the sum of the diagonal entries of this matrix as my score maybe? I could not get the standard `dtw` function to work with the above array shapes, but `cdist_dtw` does indeed.

**Comment by GillesVandewiele** [comment]
Each row in the matrix will contain the distances from one timeseries in dataset A to all other timeseries in dataset B. To get the distance from a timeseries to itself (and given that the order remained the same), then the distances you are looking for can be found on the diagonal of that distance matrix.

**Comment by rtavenar** [comment]
Hum, I think there is some misunderstanding going on here...

If you have 20 timestamps of 15 2d positions, then the features you record at each timestamp are 30d vectors, so your time series should be of shape (20, 30).
And the series in your database should be of shape (30, 30) if they record the same features for 30 timestamps.

**Comment by Duthopi** [comment]
Ah yes of course, I had not realized it was a matter of flattening the feature matrices. Thank you, I think that solves my problem :)
