### ISSUE TITLE
Question about TimeSeriesKMeans

### ISSUE THREAD

**Issue by loukotal** [rtavenar/tslearn#161]
Hi,
thanks for the package and great work you've done! I will be using your package for time series clustering in my thesis!

I would like to ask about TimeSeriesKMeans - I was not able to find how k-means works for timeseries. I am familiar with it's "normal" implementation. I would like to ask if there is a pseudocode algorithm of the inner workings of this algorithm or a resource I could read/watch to better understand it?

My apologies for spamming, I can delete it right away if needed.

Thank you.

**Comment by rtavenar** [comment]
Hi @loukotal 

Thanks for your interest in tslearn. 
The main point, when applying kmeans to time series is to pick an appropriate distance, ans to compute barycenters according to that distance (also called Frechet means). In tslearn, we allow the use of standard kmeans (with euclidean distance) or more time series specific distances such as (soft) dtw, for which barycenter computation methods ( and related bibliographical reference) are available in the barycenters module.

Hope this helps,
Romain

**Comment by rewreu** [comment]
@loukotal 
This article may helps:
https://www.researchgate.net/publication/220601732_A_global_averaging_method_for_dynamic_time_warping_with_applications_to_clustering

**Comment by loukotal** [comment]
Sorry for the late response.

Thank you both for the response! It was definitely helpful.

This issue can be closed, should I close it?

Thank you for your work!
