### ISSUE TITLE
Output from KMeans fit-predict 

### ISSUE THREAD

**Issue by rafvasq** [rtavenar/tslearn#165]
Can someone explain or point me to the documentation that explains the output from a TimeSeriesKMeans `fit_predict` method as shown in the examples? Is the red line a visualization of the best fit for the grey data displayed behind it? 

Thanks!

**Comment by rtavenar** [comment]
`fit_predict`, for a clustering algorithm, returns the cluster assignment of the data.
The red line displayed in the docs is the barycenter (aka centroid) for each cluster.
