### ISSUE TITLE
Non-uniform spelling of "timeseries"

### ISSUE THREAD

**Issue by TTitcombe** [rtavenar/tslearn#166]
There are a few different spellings of "timeseries" in various functions and classes in `tslearn`:
* **time_series**
    * e.g. `tslearn.utils.to_time_series_dataset`
* **timeseries**
    * e.g. `tslearn.utils.timeseries_to_str`
* **TimeSeries**
   * In classes, e.g. `tslearn.preprocessing.TimeSeriesResampler`

It would be useful to have a standard spelling; my suggestion would be methods and functions are `timeseries` and class names are `Timeseries`.

I would be happy to work on a PR to deprecate the old names once a standard has been decided.

**Comment by rtavenar** [comment]
Hi @TTitcombe and thank you for your feedback.

You are perfectly right that it should be homogeneized.
I kind of agree that `timeseries` is better than `time_series`, but I would keep `TimeSeries` however. Does it feel strange to you?
And an important point is that we should definitely do that in several steps (first deprecate but keep aliases to ensure backward compatibility).

**Comment by TTitcombe** [comment]
For me, **T**ime**S**eries implies it's two separate words. However, I don't think it would be an issue to keep `TimeSeries` as classes do have their own naming conventions - I've never accidentally used `Timeseries` because it's easier to remember the case for classes than it is to remember when to use `timeseries` and when to use `time_series`.

**Comment by rtavenar** [comment]
Finally I changed my mind and decided to use `TimeSeries` and `time_series` spellings throughout the package. I have pushed this to `dev` (but kept old naming in tests to check backward compatibility).

Thanks again @TTitcombe for pointing this issue, do not hesitate to check `dev` branch before release of v0.3 if you have time to see if I missed something.
