### ISSUE TITLE
DTW with stretch Constraints

### ISSUE THREAD

**Issue by santaniitr** [rtavenar/tslearn#168]
In using **metric.dtw_path** for alignment of 2 Time Series, which are **similar** but not **identical**, is it possible to include some kind of allowed stretch percentage as a constraint in finding the path?

Let's say, for the Target array, any sample will be allowed to move only (+ or - 25%) of the sample interval of the array. So find the shortest path accordingly.

For Example in this [Paper....](https://pdfs.semanticscholar.org/32b3/177dfd317e8d38fca5c5a1cb49ea3adf1d32.pdf)

**Comment by lckr** [comment]
You might want to have a look at the two already implemented constraints, i.e., the Sakoe-Chiba Band and the Itakura Parallelogram [http://www.cs.ucr.edu/~eamonn/DTW_myths.pdf](e.g. here).
It sounds to me as if the Sakoe-Chiba Band does what you are looking for.

**Comment by rtavenar** [comment]
Hi @santaniitr 

In tslearn, such constraints are set via the `global_constraint` of `dtw`. We offer, at the time of writing (v0.2.*) two such global constraints that are Itakura parallelogram and SakoeChiba band.

Itakura parallelogram is similar in spirit to what is described in Fig7 of the paper you cite (yet it is implemented in a different manner: not by changing the allowed transitions but rather by enforcing paths to lie in a parallelogram around the diagonal).

Sakoe-Chiba band probably better matches what you describe in your comment: if you set a `sakoe_chiba_radius` of 10, that means you allow series to have a maximum phase shift of 10 time stamps (or, more precisely, you will not look for paths that would imply greater time shifts).

**Comment by rtavenar** [comment]
Woops, @lckr : seems like we wrote our answers at the same time. Nice that we agree on the conclusion :)
