### ISSUE TITLE
Unable to see the strings for SAX

### ISSUE THREAD

**Issue by eemamedo** [rtavenar/tslearn#170]
I am not sure if this is a bug but I am unable to see the string representation for SAX. I can group by PAA but the whole point of SAX is to transform a series into a string representation. 

Is there something I am missing?

**Comment by rtavenar** [comment]
Hi @eemamedo 

If you use SAX transform as done below:

```python
sax = SymbolicAggregateApproximation(n_segments=n_paa_segments,
                                     alphabet_size_avg=n_sax_symbols)
dataset_sax = sax.fit_transform(dataset)
```

your variable `dataset_sax` will be made of integer indices (0, 1, 2, etc.) that are your symbols. If you really want a string, could can always map the 2d array of integers to an array of strings.
