### ISSUE TITLE
can be your code used for multivariate time series prediction

### ISSUE THREAD

**Issue by Sandy4321** [rtavenar/tslearn#172]
great code thanks
only can you clarify if
can be your code used for multivariate time series prediction
like
https://github.com/alan-turing-institute/sktime/blob/master/examples/multivariate_time_series_classification.ipynb

**Comment by Sandy4321** [comment]
can be your code used for multivariate time series classification 
for example  binary target : yes and not

**Comment by GillesVandewiele** [comment]
Hi @Sandy4321,

most (if not all) modules from tslearn can be used for multivariate timeseries. The dimensions of the data you pass should be of the shape (n_timeseries, timeseries_length, n_dimensions).

**Comment by Sandy4321** [comment]
great thanks for soon answer, good news 
then 
which code example is suitable for 
when data is mixter of continues and categorical variables for each time sample?
for example data samples are 
time t1:  red , 0.4 , big , low, 234
time t2:  green, 0.8, big, high, 12
time  t3:  green, 0.1, small, low, 34
etc

**Comment by choltz95** [comment]
Is it possible to do some kind of initial preprocessing of your categorical variables? e.g. one hot encoding & apply to standard methods should be okay.

You can also apply one of the kernel methods & choose an appropriate kernel which can handle the categorical features...I forget the details, but you can see what the popular hyperparameter opt. packages do in this case.

**Comment by Sandy4321** [comment]
do you have this data
when data is mixer of continues and categorical variables for each time sample?
for example data samples are
time t1: red , 0.4 , big , low, 234
time t2: green, 0.8, big, high, 12
time t3: green, 0.1, small, low, 34
etc
to try your idea 
and

I found some refernce
https://www.cs.toronto.edu/~duvenaud/cookbook/

Discrete Data
Kernels can be defined over all types of data structures: Text, images, matrices, and even kernels . Coming up with a kernel on a new type of data used to be an easy way to get a NIPS paper.
How to use categorical variables in a Gaussian Process regression
There is a simple way to do GP regression over categorical variables. Simply represent your categorical variable as a by a one-of-k encoding. This means that if your number ranges from 1 to 5, represent that as 5 different data dimensions, only one of which is on at a time.

Then, simply put a product of SE kernels on those dimensions. This is the same as putting one SE ARD kernel on all of them. The lengthscale hyperparameter will now encode whether, when that coding is active, the rest of the function changes. If you notice that the estimated lengthscales for your categorical variables is short, your model is saying that it's not sharing any information between data of different categories


but it is not clear

there is even code
https://github.com/Lkxz/categorical-kernels
and thesis
https://upcommons.upc.edu/bitstream/handle/2099.1/24508/99930.pdf?sequence=1

or
https://www.researchgate.net/post/What_kernel_functions_can_be_applied_to_categorical_features
However, if you would like to use kernel function for categorical data, I think this package [1] might be helpful. In particular, for categorical data, you could use Aitchison-Aitken kernel [2].
[1] http://socserv.mcmaster.ca/racine/Rjournal.pdf
[2] http://biomet.oxfordjournals.org/content/63/3/413.abstract
or
https://academic.oup.com/biomet/article-abstract/63/3/413/270829
