### ISSUE TITLE
Adding warping window size to the DTW-related algorithms

### ISSUE THREAD

**Issue by Ninimama** [rtavenar/tslearn#176]
First of all, thanks a lot for creating this amazing package. I am a Ph.D. student in Electrical Engineering and implementing such algorithms on my own would take a lot of time since I don't how to write a program efficiently!
I think the "warping window size" is missing from the package which can be helpful. According to Dr. Keogh and Dr. Abdullah Mueen, some time series data have only one particular warping path in which the clustering/classification has higher performance.
So, it would be a good idea to add the warping window size as an argument to the functions related to DTW.

See: https://www.cs.unm.edu/~mueen/DTW.pdf
(page 33/123)

**Comment by Ninimama** [comment]
First of all, thanks a lot for creating this amazing package. I am a Ph.D. student in Electrical Engineering and implementing such algorithms on my own would take a lot of time since I don't how to write a program efficiently! 
I think the "warping window size" is missing from the package which can be helpful. According to Dr. Keogh and Dr. Abdullah Mueen, some time series data have only one particular warping path in which the clustering/classification has higher performance. 
So, it would be a good idea to add the warping window size as an argument to the functions related to DTW.   

See: https://www.cs.unm.edu/~mueen/DTW.pdf 
(page 33/123)

**Comment by rtavenar** [comment]
Hi @Ninimama 

Such a constraint is a global constraint denoted `"sakoe_chiba"` in tslearn.
You can find out more in [the docs](https://tslearn.readthedocs.io/en/latest/gen_modules/metrics/tslearn.metrics.dtw.html).
A more detailed doc dedicated to DTW should be available soon, we are working on it (ongoing work available [here](https://github.com/rtavenar/tslearn/blob/dev/tslearn/docs/dtw.rst)).

Best regards,
Romain
