### ISSUE TITLE
Handling varying length timeseries is missed for unsupervised K nearest neighbors

### ISSUE THREAD

**Issue by prakass1** [rtavenar/tslearn#181]
Thank you first of all for providing such a library for implementation.

**Describe the bug**
I would not really call it a bug. I am using version 0.2.5 of tslearn. I could see from the source that there has been handling of variable-length time series for the classification task of KNeighborsTimeSeriesClassifier class. However, I do not see it being used for unsupervised knn. Is there any reason for not adding the same functionality in the KNeighborsTimeSeries?

**To Reproduce**
X = to_time_series_dataset([[1, 2, 3, 4], [1, 2, 3], [2, 5, 6, 7, 8, 9]])
knn = KNeighborsTimeSeries(n_neighbors=2)
knn.fit(X)
**Error**
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - tslearn version [0.2.5]

**Comment by GillesVandewiele** [comment]
This could indeed be handled better. If you are just interested in getting the closest neighbours to certain timeseries, you can use the `kneighbors` function https://github.com/rtavenar/tslearn/blob/1721482c2bb3539e3fdef3d4456f7c580489b44b/tslearn/neighbors.py#L24

**Comment by prakass1** [comment]
@GillesVandewiele, thank you for the reply. I am not sure if I completely got the idea.
The use case which I working at is to match a time-series data sent from the application to the existing time series of the database. Since, I do not have the label I thought I would first need to fit a nearest neighbor with some k and then find kneighbors to the query sent from the application. But for the fit, I have the issue with varying length time-series. Please let me know if there something that requires to be changed in the approach.

**Comment by rtavenar** [comment]
Hi @prakass1 

Thanks for your feedback. Indeed, we dealt with variable length series for regression and classification but not for search. I will patch it later today, and it will be available on `dev` branch. It will be available on pip as soon as v0.3 is out!

Best regards,
Romain

**Comment by prakass1** [comment]
Hi @rtavenar

Thanks a lot for your reply.

Thanks,
Subash
