### ISSUE TITLE
use of prange

### ISSUE THREAD

**Issue by jw-rs** [rtavenar/tslearn#184]
**Describe the bug**
Numba's prange is being used where there are cross-iteration dependencies.

Hi there,

Just thought I'd point out that there are calls to 'prange' in tslearn/metrics.py which have cross-iteration dependencies. For example, in current master, lines 60/61, 574/575, etc.

Depending on the order the parallel loops are run, this could lead to inconsistent results.

**Comment by rtavenar** [comment]
Hi @jw-rs and thanks for this.

I thought `numba` was supposed to deal with such dependencies. 

@johannfaouzi : do you know if there i a risk there?

**Comment by johannfaouzi** [comment]
Citing [numba documentation](https://numba.pydata.org/numba-doc/dev/user/performance-tips.html#parallel-true):

> Numba parallel execution also has support for explicit parallel loop declaration similar to that in OpenMP. To indicate that a loop should be executed in parallel the numba.prange function should be used, **this function behaves like Python range and if parallel=True is not set it acts simply as an alias of range**. Loops induced with prange can be used for embarrassingly parallel computation and also reductions.

So it's fine as it is because `parallel=True` is not set in the `njit()` decorator.

**Comment by jw-rs** [comment]
> I thought numba was supposed to deal with such dependencies.

From https://numba.pydata.org/numba-doc/latest/user/parallel.html: 
"One can use Numba’s prange instead of range to specify that a loop can be
parallelized. **The user is required to make sure that the loop does not have cross iteration dependencies except for supported reductions.**"

> So it's fine as it is because parallel=True is not set in the njit() decorator.

True; hadn't noticed the decorator. Note that prange() is incorrect in the context of these loops, so it might be worth changing to range(). But yes, sorry, without parallel=True, it's not a bug.
