### ISSUE TITLE
TimeSeriesScalerMeanVariance returns extra dimension then documentation

### ISSUE THREAD

**Issue by adam2392** [rtavenar/tslearn#185]
**Describe the bug**
TimeSeriesScalerMeanVariance returns 3 dimensions, when the data matrix (N x T) is 2 dimensions. 

**To Reproduce**

```
X = np.random.random((87,120))
print(X.shape)
X = TimeSeriesScalerMeanVariance().fit_transform(X)
print(X.shape)
```

**Expected behavior**
It should be squeezed, or at least better documentation.

**Additional context**
Happy to submit a PR for this, but want to know if the problem is in documentation, versus just better squeeze output after `fit_transform`?

**Comment by rtavenar** [comment]
Hi @adam2392 and thanks for this report. This is in fact an expected behaviour since a dataset is supposed to be 3d on tslearn. 

But you are perfectly right that the docs should make that clearer. I will fix this asap.

Best regards 
Romain
