### ISSUE TITLE
ZeroDivisionError with SAX, PAA and 1-d SAX transfortmation

### ISSUE THREAD

**Issue by f43g** [rtavenar/tslearn#187]
Hi,
i saw the code for SAX, PAA and 1-d SAX transfortmation. For example, using this block of code:

`# PAA transform (and inverse transform) of the data`
`n_paa_segments = 10`
`paa = PiecewiseAggregateApproximation(n_segments=n_paa_segments)`
`paa_dataset_inv = paa.inverse_transform(paa.fit_transform(dataset))`

with my datasets (that are a numpy array of integers or floats) returns every time this error:

ZeroDivisionError: integer division or modulo by zero

**Comment by GillesVandewiele** [comment]
Hi,

What's the shape of dataset?

The input should be 3D:
```
X : array-like of shape (n_ts, sz, d)
            Time series dataset
```

But there is no type checking currently present in the PiecewiseAggregateApproximation or SymbolicAggregateApproximation, which should normally be fixed in a future PR.

**Comment by f43g** [comment]
Probably is not a 3D dataset.
For example this one, where i extract the Price column:
https://www.macrotrends.net/1320/nasdaq-historical-chart

Is there a way to reshape it?

**Comment by GillesVandewiele** [comment]
Yes, you can reshape it before feeding it to tslearn (e.g. with numpy.reshape)

**Comment by f43g** [comment]
Thank you!!
