### ISSUE TITLE
Generate wiki pages for contributors (docs, tests, pep-8, ...)

### ISSUE THREAD

**Issue by GillesVandewiele** [rtavenar/tslearn#195]
We should create some wiki pages on how contributors can locally do different things that are automated in this repository (with corresponding scripts). I often push stuff to check on my changes, bcs I don't know how to do it locally, which is of course not optimal.

* How to build documentation 
* How the different tests & doctests can be ran
* Pep-8 flaking
* ...

**Comment by johannfaouzi** [comment]
scikit-learn has a very detailed [Contributing](https://scikit-learn.org/stable/developers/contributing.html) page. [Here](https://pyts.readthedocs.io/en/stable/contribute.html) is a shorter version that I did for pyts.

Just to give some ressources if someone has some time to work on this (I could work on it later if no one did it).

**Comment by johannfaouzi** [comment]
There is a [CONTRIBUTING.md](https://github.com/rtavenar/tslearn/blob/master/CONTRIBUTING.md) file at the root of the repository but:
* It is not present in the documentation on RTD;
* There is nothing about running tests or building the documentation locally (the commands are really simple).

What do you think @rtavenar? I think that it should be relatively easy to extend this page and put it in the documentation. We would just need to:
* decide where to put it in the documentation;
* convert it to RST from MD;
* extend the **Pull Request checklist** section with running the tests and building the documentation locally.

**Comment by rtavenar** [comment]
100% agree. I guess this page could be listed in the Table of Contents in the menu bar of the docs, WDYT @GillesVandewiele @johannfaouzi ? If so, it should be added [there (end of the document)](https://github.com/rtavenar/tslearn/blob/master/tslearn/docs/index.rst).

**Comment by GillesVandewiele** [comment]
@rtavenar Yes I think it should definitely be highlighted in the docs.

@johannfaouzi Indeed, some clear guidelines/checklist on how to run the tests & build the docs locally would be great (perhaps even a bash script that does this all for you locally)

**Comment by rtavenar** [comment]
I guess I can close this one since #197 was merged, can I ?
