### ISSUE TITLE
Find synergies with tsfresh / tspreprocess

### ISSUE THREAD

**Issue by MaxBenChrist** [rtavenar/tslearn#2]
Hi @rtavenar,

I am impressed with the number of algorithms you already implemented in *tslearn*.  Actually, I had the idea for the same package, even the same name :D :D. Some of the algorithms I implemented in the past.

I have been working with time series models for the last years and there is definitely a lack of python tools or ecosystems for time series analysis. So, I designed both packages https://github.com/blue-yonder/tsfresh and https://github.com/MaxBenChrist/tspreprocess.

If you are interested, I would like to have a chat with you to hear your ideas and vision for *tslearn*. We have a really good development team in tsfresh. Maybe we find a way to synchronize our efforts and  support you.

Best, Max

**Comment by rtavenar** [comment]
Yes, that would be great. Would next Wednesday (during Western Europe office hours) be OK for you? I could maybe join your gitter.

**Comment by MaxBenChrist** [comment]
Next Wednesday sounds good. Can you send me a personal message on gitter?

**Comment by rtavenar** [comment]
So, after the call, @MaxBenChrist has published [a list of github repositories](https://github.com/MaxBenChrist/awesome_time_series_in_python) that provide tools for the analysis of time series.
The idea is that, at some point, it would be nice to gather people from this repos and see if it seems feasible to propose a uniform representation for time series across all these tools.
If this works well, further collaboration could be considered.

**Comment by MaxBenChrist** [comment]
> So, after the call, @MaxBenChrist has published a list of github repositories that provide tools for the analysis of time series.
The idea is that, at some point, it would be nice to gather people from this repos and see if it seems feasible to propose a uniform representation for time series across all these tools.
If this works well, further collaboration could be considered.

Thanks again for the nice call.

Yes, I am planning to extend the list to get an overall overview. Regarding the collaboration, as you said, I think we should focus on the formats for now.

**Comment by rtavenar** [comment]
In #149 , we have added conversion functions between several Python libs for time series, including `tsfresh`. Already available in `dev` branch, will be included from version 0.3
