### ISSUE TITLE
TimeSeriesKMeans and variable length time series

### ISSUE THREAD

**Issue by rtavenar** [rtavenar/tslearn#21]
I received the following by e-mail, and I prefer to deal with it through a GitHub issue.

> Dear Dr Tavenard
> Today I started with using tslearn.
> My small home project is about trying to cluster time series data. I have data from my own cycling. These are various rides I made. From each ride file I extracted 1 time series (namelijk wattage). My rides are from various lenght so my time series are from various length.
> I have already put my rides in the right data format for tslearn using:
> 
> ```python
> >>> from tslearn.utils import to_time_series_dataset
> >>> formatted_dataset = to_time_series_dataset(appended_data_Garmin)
> ```
> 
> As expected I get nan for filling up all the datapoints given the longest time series I have. 
> However. When I try to run the simple:
> 
> ```python
> >>> from tslearn.clustering import TimeSeriesKMeans
> >>> km = TimeSeriesKMeans(n_clusters=3, metric="dtw", max_iter=5, verbose=False, random_state=0)
> >>> km.fit(formatted_dataset)
> ```
> 
> I get: 
> ```
> ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
> ```
> 
> Do you have any idea what might be causing this issue?

**Comment by rtavenar** [comment]
Should now be fixed. Please re-open if not.

**Comment by MAGomes95** [comment]
Hello,

Today is was having the exact same problem.
When trying to cluster different length different series data with TimeSeriesKMeans, despite the n_cluster argument given and the number of time series at hand, the total number of clusters is at maximum 2.

**Comment by rtavenar** [comment]
@MAGomes95 I doubt this could be the same issue, please open a New issue to describe your problem with minimal reproducing example.
