### ISSUE TITLE
sklearn.neighbors.base is being deprecated

### ISSUE THREAD

**Issue by beeb** [rtavenar/tslearn#214]
Apparently `sklearn` is deprecating the `neighbors.base` module, but `tslearn` still uses `KNeighborsMixin` in `tslearn.neighbors`.

I guess this inheritance will need to be reworked before `sklearn == 0.24` to make sure everything works.

Just thought I'd let you guys know because I get warnings about this ;)

**Comment by rtavenar** [comment]
Thank you very much, this is a great idea to let us know via a github issue. We're on it #211 😉

**Comment by beeb** [comment]
Great! Thanks for your work
