### ISSUE TITLE
No module named 'tslearn.soft_dtw_fast' when importing tslearn.metrics

### ISSUE THREAD

**Issue by mustafadgr** [rtavenar/tslearn#218]
**Describe the bug**
I can't import tslearn.metrics

**To Reproduce**
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-95-d750b1add255> in <module>
      8 import moviepy.editor as mp
      9 from IPython.display import Video
---> 10 import tslearn.metrics as tsm

~/491/python/project_env/lib/python3.7/site-packages/tslearn-0.3.1-py3.7-macosx-10.15-x86_64.egg/tslearn/metrics.py in <module>
     11 from sklearn.metrics.pairwise import euclidean_distances
     12 from sklearn.utils import check_random_state
---> 13 from tslearn.soft_dtw_fast import _soft_dtw, _soft_dtw_grad, \
     14     _jacobian_product_sq_euc
     15 

ModuleNotFoundError: No module named 'tslearn.soft_dtw_fast'
```

**Expected behavior**
import the library

**Environment (please complete the following information):**
macos version: 10.15.4
python version: 3.7.6
tslearn 0.3.1

**Additional context**
I specifically want to use DTW metrics

**Comment by GillesVandewiele** [comment]
Make sure to run the `setup.py` script. You did not create a script in the `tslearn` directory itself right (because that could cause issues as well)?

**Comment by mustafadgr** [comment]
> This looks like your `tslearn` is not properly installed.
> 
> I have just uploaded a bunch of wheels for all platforms on PyPI, which should make it easier to install on diverse platforms.
> Could you try to uninstall your tslearn and then reinstall it from PyPI and tell us if that works, and, if not, give us the output you get?

https://github.com/rtavenar/tslearn/issues/196
I installed tslearn from github manually since I had this issue. I uninstalled it now and run the pip command:
`sudo python3 -m pip install tslearn `
now it works! thanks

**Comment by rtavenar** [comment]
This is great news !

**Comment by rtavenar** [comment]
This is great news !
