### ISSUE TITLE
UCR_UEA_datasets.baseline_accuracy fail for list_datasets=None

### ISSUE THREAD

**Issue by rth** [rtavenar/tslearn#23]
(originally posted as part of #22 )

With Python 3 and tslearn 0.1.10.8 after loading all datasets, and running `d.load_dataset('ItalyPowerDemand')` I'm getting an error for,
```py
>>> d.baseline_accuracy()
ValueError                                Traceback (most recent call last)
-> 1 d.baseline_accuracy()

~/anaconda2/envs/ts-env/lib/python3.6/site-packages/tslearn/datasets.py in baseline_accuracy(self, list_datasets, list_methods)
    149                 for m in perfs_dict.keys():
    150                     if m != "" and (list_methods is None or m in list_methods):
--> 151                         d_out[perfs_dict[""]][m] = float(perfs_dict[m])
    152         return d_out
    153 

ValueError: could not convert string to float: 
```
while `d.baseline_accuracy('ItalyPowerDemand')` works as expected. I guess some input validation is missing ..

**Comment by rtavenar** [comment]
Thanks for reporting it!

I'll have a look when I have time, which is not right now unfortunately. 

If someone feels like fixing that, it should not be too difficult (adding proper doctest would be a plus :) ), unless it is related to corrupted downloaded file, for which support is not satisfactory at the moment.

**Comment by rth** [comment]
Thanks for your response. 

>  it should not be too difficult (adding proper doctest would be a plus :) ), unless it is related to corrupted downloaded file, for which support is not satisfactory at the moment.

Since it's able to unzip the downloaded file and extract at least one dataset, I think it's probably the former.

**Comment by rtavenar** [comment]
Fixed
