### ISSUE TITLE
AttributeError: 'ShapeletModel' object has no attribute 'get_params'

### ISSUE THREAD

**Issue by jscheithe** [rtavenar/tslearn#29]
If i run this from command line:
```
from tslearn.shapelets import ShapeletModel
sm = ShapeletModel({1:1})
sm.get_params()
```
i get
```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
AttributeError: 'ShapeletModel' object has no attribute 'get_params'
```

However, if i run the file from Spyder in IPython, it works as expected.

Same thing happens with `sm.set_params(batchsize=128)`, but calling `sm.fit(X, y)` works from command line as well as from IPython console.

Strange, right? Do you have any idea what might cause this?

EDIT: For the record, not all estimators from tslearn are afffected:
```
from tslearn.shapelets import ShapeletModel
from tslearn.clustering import TimeSeriesKMeans

tskm = TimeSeriesKMeans()
sm = ShapeletModel({1:1})

print(tskm.get_params())
print(sm.get_params())
```
```
{'dtw_inertia': False, 'max_iter': 50, 'max_iter_barycenter': 100, 'metric': 'euclidean', 'metric_params': None, 'n_clusters': 3, 'n_init': 1, 'random_state': None, 'tol': 1e-06, 'verbose': True}
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    print(sm.get_params())
AttributeError: 'ShapeletModel' object has no attribute 'get_params'
```

**Comment by rtavenar** [comment]
Hi @jscheithe 

Well, I don't really understand why... this worked for IPython :)

In fact, I had not inherited from `sklearn` base classes which is why `get_params` and `set_params` were not set. Now it should be, and I added it to the doctests in order to check the correct behaviour of these methods.

Let me know if this fits your need.

**Comment by jscheithe** [comment]
Haha, I'm stupid.
The reason it worked in IPython was, that it worked on my local machine (I added the inheritance some time ago manually, but forgot about it).

Now it also works on my remote server. Thanks for pointing it out/fixing this!
