### ISSUE TITLE
Notes on Barycenter API

### ISSUE THREAD

**Issue by unnamedplay-r** [rtavenar/tslearn#31]
A few notes:
1. After putting the Barycenter API to use, it feels weird calling `.fit()` and returning an average sequence. `.fit()` feels like it would initiate the initial average sequence through some method and perform initial computations. The `transform()` method feels right more right here, it would take those computations and perform the transformation of the dataset into an average sequence.
2. In the documentation of the DBA algorithm, it's not clear what EM means in the `max_iter`, `init_barycenter`, and `tol` parameters.
3. In the DBA algorithm, you raise an error if the sequence doesn't converge and begins to backpedal:
https://github.com/rtavenar/tslearn/blob/7d1f00ca0b647d9c5e4ce6bd34c7b97038abec80/tslearn/barycenters.py#L150-L151 This feels like bad practice. If I'm waiting hours for a dataset to converge, I would die a little bit on the inside if I found an error was raised and all that computational effort went to nothing. This should instead print out a [convergence error warning](http://scikit-learn.org/stable/modules/generated/sklearn.exceptions.ConvergenceWarning.html#sklearn.exceptions.ConvergenceWarning) and return the average sequence.

**Comment by rtavenar** [comment]
Hi @unnamedplay-r 

Thanks for your interest in `tslearn`.

Here are my answers:

1. I don't really know which one is best. Definitely, `.fit()` is not ideal since in `sklearn` it is supposed to return the estimator itself, while in this case it returns the barycenter. One more thing that bothers me is that we will have to break compatibility. So I'll try to think about this a bit more before making my decision.
2. OK, I'll fix that
3. You're right, it was for me to ensure that everything went right when coding the method, but it should not be there anymore

**Comment by rtavenar** [comment]
OK, since v0.1.15, barycenters are no longer estimators (classes that existed up to now will be deprecated in v0.2).

**Comment by unnamedplay-r** [comment]
Hi @rtavenar,

It's a pleasure, you've built up a wonderful time series toolset here, and it's exciting to see the development of more TS tools in Python!

1. Yeah, I don't see anything relevant in sklearn's API that takes in data and makes a reduction of the data set. Anything that isn't an estimator or a transformer is in it's own function or class with dedicated methods. I'm thinking the API can take on more of a new form, similar to what was done on the imbalanced-learn project ([example API](http://contrib.scikit-learn.org/imbalanced-learn/stable/generated/imblearn.under_sampling.CondensedNearestNeighbour.html#imblearn.under_sampling.CondensedNearestNeighbour)). Here they generated a new API using new [base classes](https://github.com/scikit-learn-contrib/imbalanced-learn/blob/master/imblearn/base.py). A thought here: As more full data transformation algorithms come into play, it might be worth to define a new abstract class with uniform methods that take in a full dataset and return an entirely new data structure of some shape. Abstract algorithms that operate on the data structure would also need to be defined.
2. Thanks for clearing that up.
3. I'd suggest breaking to return the average sequence if the implementation begins backpedaling in addition to the warning. Guaranteed convergence is an amazing feature of the DBA and if we see any start of it backpadeling, I don't think we should trust the the implementation to return to a stable point enough where the tolerance is lower enough to return the sequence.

**Comment by rtavenar** [comment]
Implemented your suggestion for 3.

For 1., I'm not fully convinced of what a new abstract class would provide that we don't have with the function-based implementation at the moment. If at some point, we find other cases in which this would make sense, we should definitely think about it more thoroughly.

**Comment by unnamedplay-r** [comment]
Wonderful, this is much more sensible.

As for 1, I agree, this would be better to consider this at a later point.

Thanks for being so welcoming and responsive @rtavenar!
