### ISSUE TITLE
[Bug] dtw_barycenter_averaging function default parameters incorrectly set

### ISSUE THREAD

**Issue by unnamedplay-r** [rtavenar/tslearn#32]
https://github.com/rtavenar/tslearn/blob/0aeeb125606f63eb64d6112b61cf7252a8fd62fa/tslearn/barycenters.py#L263-L264

max_iter needs to be set to an integer, and by the docs and previous implementation, it's 30.

**Comment by rtavenar** [comment]
Thanks for reporting it.
Fixed since version 0.1.16.2 + added a doctest to check that for future versions.
