### ISSUE TITLE
ShapeletsModel's catagorical_accuracy doesn't change with binary classification

### ISSUE THREAD

**Issue by zixuanweeei** [rtavenar/tslearn#34]
Use the docs/examples/plot_shapelet.py, and modify the `y_train` to be suitable for binary classification tasks. I think this can reproduce the bug.

**Comment by rtavenar** [comment]
Hi @zixuanweeei ,

Are you sure you use the latest `tslearn` version?
On my side, if I add :

```


X_train = X_train[y_train<=2]
y_train = y_train[y_train<=2]
X_test = X_test[y_test<=2]
y_test = y_test[y_test<=2]
```

in the `docs/examples/plot_shapelet.py` script after loading the data, it works well:
```
> print(shp_clf.model.loss)
binary_crossentropy
```

**Comment by zixuanweeei** [comment]
tflearn == 0.1.16.2, keras == 2.0.6, tensorflow == 1.8.0

In the `docs/examples/plot_shapelet.py` script, I modify the line 41 to `verbose_level=2)` and add the four lines for binary classification task. And it displays:
```
Epoch 1/200
0s - loss: 0.7142 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 2/200
0s - loss: 0.6778 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 3/200
0s - loss: 0.6583 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 4/200
0s - loss: 0.6415 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 5/200
0s - loss: 0.6183 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 6/200
0s - loss: 0.5972 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 7/200
0s - loss: 0.5787 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 8/200
0s - loss: 0.5610 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 9/200
0s - loss: 0.5463 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
Epoch 10/200
0s - loss: 0.5296 - categorical_accuracy: 1.0000 - categorical_crossentropy: 6.3181e-08
...
```

The `catagorical_accuracy` is always `1.0000`. But the result looks correct.

**Comment by rtavenar** [comment]
Hi,

OK, I didn't get your point in fact. Well, if it's already 100% accurate at the first iteration (ie. after the initialization process), it's good news that it does not get worse afterwards :)

Best,
Romain

**Comment by zixuanweeei** [comment]
Hi,

OK. Sorry about making you confused. To make it clear, I set the max iteration `max_iter=1` which is parameter of the `ShapeletModel` API. And I use the `X_train`'s feature to predict. The output is:

```
Epoch 1/1
0s - loss: 0.6926 - categorical_accuracy: 1.0000 - categorical_crossentropy: 5.3264e-08
Correct classification rate: 0.5531914893617021
```
The `categorical_accuracy` doesn't match the correct classification rate.

**Comment by rtavenar** [comment]
Ah OK!

Now it's fixed then :)

Thanks for the bug report, it helped make `tslearn` better!
