### ISSUE TITLE
bug in release version 0.1.14

### ISSUE THREAD

**Issue by rhoposit** [rtavenar/tslearn#37]
```
from tslearn.clustering import KShape,TimeSeriesKMeans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tslearn-0.1.14-py2.7-macosx-10.11-intel.egg/tslearn/clustering.py", line 13, in <module>
    from tslearn.metrics import cdist_gak, cdist_dtw, cdist_soft_dtw, dtw
  File "/Library/Python/2.7/site-packages/tslearn-0.1.14-py2.7-macosx-10.11-intel.egg/tslearn/metrics.py", line 8, in <module>
    from tslearn.soft_dtw_fast import _soft_dtw, _soft_dtw_grad, _jacobian_product_sq_euc
  File "__init__.pxd", line 164, in init tslearn.soft_dtw_fast
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
>>> 
```

re-compiled, re-installed and now:
```
from tslearn.clustering import KShape,TimeSeriesKMeans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tslearn/clustering.py", line 13, in <module>
    from tslearn.metrics import cdist_gak, cdist_dtw, cdist_soft_dtw, dtw
  File "tslearn/metrics.py", line 8, in <module>
    from tslearn.soft_dtw_fast import _soft_dtw, _soft_dtw_grad, _jacobian_product_sq_euc
ImportError: No module named soft_dtw_fast
```

You've got a `soft_dtw_fast.c` and a `soft_dtw_fast.pyx` -> is there supposed to also be a `soft_dtw_fast.py`?

**Comment by rtavenar** [comment]
Hi @rhoposit ,

Thanks for reporting this bug. I'm not an expert in how `pip` packages stuff, but it seems you should not need `.py` file.
Do you have `Cython` installed? Coud you try installing it and tell me if this fixes the issue or not?

Thanks in advance,
Romain

**Comment by rtavenar** [comment]
No news, closing.

**Comment by ziad1988** [comment]
Hello , 
I have faced the same issue when installing tslearn package : ' No module named 'tslearn.soft_dtw_fast'
I tried using pip install tslearn then I had to manually install the package and run a python setup.py
However I got this error :  No module named 'tslearn.soft_dtw_fast' . When I check the files , I don't see any tslearn.soft_dtw_fast.py , I see a tslearn.soft_dtw_fast.pyc. 
I am on python 3.7.4 , could you help please
Thanks,
