### ISSUE TITLE
pip out of date

### ISSUE THREAD

**Issue by brandly** [rtavenar/tslearn#4]
hey, i'm having trouble installing this with `pip`, which i believe [this commit](https://github.com/rtavenar/tslearn/commit/7f3e66f6e673cb06f5b01634156ca9a5e38c1827) might fix.

the latest version i see in the [releases](https://github.com/rtavenar/tslearn/releases) is v0.0.27, but the latest i see on pip is v0.0.25.

could you update the pip package? thanks! ⭐️

**Comment by rtavenar** [comment]
Hi,

Thanks for the info. I just upgraded the version hosted on pip, it should be ok now.

I leave the issue open since it seems automatic PyPI distribution does not work for the project at the moment. If anyone that knows a bit on the topic could help, that would be great!

**Comment by MaxBenChrist** [comment]
> I leave the issue open since it seems automatic PyPI distribution does not work for the project at the moment. If anyone that knows a bit on the topic could help, that would be great!

We have similar issue https://github.com/blue-yonder/tsfresh/issues/110

**Comment by MaxBenChrist** [comment]
Our travis stopped to deploy to pypi at some point.

We solved this problem in this commit

https://github.com/blue-yonder/tsfresh/commit/25f1240e9844967d2a8b05fd6d01e6b00ca82a86

I compared it to your travis.yml. You are for example missing the `distributions: "sdist bdist_wheel"` line

**Comment by rtavenar** [comment]
Thanks for the tip!

The bug is now fixed since [this commit](https://github.com/rtavenar/tslearn/commit/38fac5c6534e133dbd7e1adbc82aa2414b3547b3).
