### ISSUE TITLE
extract_from_zip_url failing on Windows

### ISSUE THREAD

**Issue by unnamedplay-r** [rtavenar/tslearn#41]
https://github.com/rtavenar/tslearn/blob/702bbb24b5a85ee0857717c60d39bb60cafca291/tslearn/datasets.py#L38

leads to a `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Adiac.zip'` error message.

I'd recommend searching for the temporary directory using the [tempfile](https://docs.python.org/3/library/tempfile.html) module and the [gettempdir](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) method, or building a temporary directory using the the [TemporaryDirectory](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) method. The TemporaryDirectory method seems like a safer and future-proof bet.

**Comment by rtavenar** [comment]
Hi and thanks once again for your bug reports,

It seems we have a fix. Could you test it on Windows and tell me if it works (we don't have windows machines running tslearn tests in Travis CI at the moment)?

**Comment by unnamedplay-r** [comment]
I encountered this problem via the `load_dataset` method in the `UCR_UEA_datasets` class, and this is working without a hastle. Thanks again for fixing this up!
