### ISSUE TITLE
Silhouette score breaks for the variant length time series

### ISSUE THREAD

**Issue by nikhilRP** [rtavenar/tslearn#43]
Hello @rtavenar,

Thank you for fixing #38 , unfortunately something similar also happens for Silhouette score.

Example to keep it simple, even though it doesn't make much sense
```
from tslearn.clustering import silhouette_score
from tslearn.metrics import soft_dtw

ts = [[1, 2, 3], [4, 5, 6, 7], [8, 7, 4, 3, 2, 1]]
labels = [1, 0, 1]
print(silhouette_score(ts, labels, metric=soft_dtw))
```

Error:

`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
`

**Comment by rtavenar** [comment]
Hi,

Thanks for your new bug report. I've commited a (partial fix) that should make it for a first step.

If you change your example into:

```python
from tslearn.clustering import silhouette_score

ts = [[1, 2, 3], [4, 5, 6, 7], [8, 7, 4, 3, 2, 1]]
labels = [1, 0, 1]
print(silhouette_score(ts, labels, metric="softdtw"))
```

This shoud work (next step is to provide `gamma` as `metric_param` option, I'm working on it, should come pretty soon).

**Comment by nikhilRP** [comment]
@rtavenar Wonderful, it works thanks.
