### ISSUE TITLE
Implement (Stochastic) Subgradient Mean

### ISSUE THREAD

**Issue by unnamedplay-r** [rtavenar/tslearn#44]
**Summary:**
Stochastically explore the DTW Averaging Space. It's a useful algorithm for exploring online settings and larger sample sizes. The paper is a bit of work to get through as they rigerously detail a connection between the DTW sample mean to nonsmooth optimization methods for their proposed algorithm. They 
also detail a non-stochastic subgradient method and present a vectorized version of DBA that might provide additional performance benefits (I'll create a seperate issue for refactoring DBA to that).

I think this package would benefit greatly for both the Subgradient (SG) and Stochastic Subgradient (SSG) methods.

**Original Paper:**
_Nonsmooth Analysis and Subgradient Methods for Averaging in Dynamic Time Warping Spaces_
- arxiv pdf: https://arxiv.org/pdf/1701.06393.pdf
- Final version of paper (paywall): https://www.sciencedirect.com/science/article/pii/S0031320317303163

Relevant sections are _4.1. The Subgradient Mean Algorithm_ and _4.3. The Stochastic Subgradient Mean Algorithm_ and their respective algorithms 1 and 3.

**Comment by rtavenar** [comment]
It is now merged to `dev`, and will be included in tslearn from version 0.3.
Thanks @unnamedplay-r for the ref!
