### ISSUE TITLE
Consider refactoring DBA to Majorize-Minimize Mean Algorithm

### ISSUE THREAD

**Issue by unnamedplay-r** [rtavenar/tslearn#45]
Referencing issue #44, DBA can be expressed in matrix and vectorized terms that might be more suited for numpy's vectorized operations. I think it would be worthwhile to explore this to see if we can get a considerable performance boost by expressing the function in this form.

Instead of removing the internals of the original algorithm, it might be worth considering adding a parameter to the function which takes values such as `'mm'` or `'original'` to differentiate what kind of internal operation it uses: either the form in the **original** paper, or the **MM** expression of the algorithm.

Relevant section in the Schultz & Jain (2017) paper is _4.2. The Majorize-Minimize Mean Algorithm_ and it's respective algorithm: 2.

**Comment by rtavenar** [comment]
It is now the default for DBA on `dev` branch, and will be included in tslearn from version 0.3.
Thanks @unnamedplay-r for the ref, computations are now twice faster in my tests!

**Comment by unnamedplay-r** [comment]
Yay! This is so wonderful @rtavenar, I’m grateful you took the recommendation into consideration.
