### ISSUE TITLE
Soft-DTW Barycenter init parameter isn't documented

### ISSUE THREAD

**Issue by unnamedplay-r** [rtavenar/tslearn#46]
See the [docs](https://tslearn.readthedocs.io/en/latest/gen_modules/barycenters/tslearn.barycenters.softdtw_barycenter.html).

**Comment by GillesVandewiele** [comment]
Good call. I just inspected the source-code to figure out what it is used for (note that I don't even know what a Barycenter is, so this is just a guess).

```
    if init is None:
        if check_equal_size(X_):
            barycenter = euclidean_barycenter(X_, weights)
        else:
            resampled_X = TimeSeriesResampler(sz=X_.shape[1]).fit_transform(X_)
            barycenter = euclidean_barycenter(resampled_X, weights)
    else:
        barycenter = init
```

So I guess the init-parameter is used when you already pre-computed this guy called Barycenter, else, it will calculate it for you.

**Comment by rtavenar** [comment]
Thanks for the report. Should be fixed now.

**Comment by unnamedplay-r** [comment]
Thanks @rtavenar!

@GillesVandewiele, you're correct. A _barycenter_ is just a average (aka mean, center) of a time-series sample. The use of barycenter in this package most likely stems from one of the more tractable averaging algorithms that uses the DTW measure, [DBA](https://tslearn.readthedocs.io/en/latest/gen_modules/barycenters/tslearn.barycenters.dtw_barycenter_averaging.html#) (DTW __Barycenter__ Averaging).
