### ISSUE TITLE
TimeSeriesScalerMinMax need a transform method

### ISSUE THREAD

**Issue by StevenLOL** [rtavenar/tslearn#48]
Hi,

Like MinMaxScaler in scikitlearn , a transform method is needed for TimeSeriesScalerMinMax.

**Comment by rtavenar** [comment]
Hi,

In practice, the reason why we have not implemented this feature in `tslearn` is exactly so that users do not misunderstand what `TimeSeriesScalerMinMax` does: it does not scale each feature (across the dataset) to lie in [0, 1]. It scales each time series so that its features lie in [0, 1].

**Comment by jamesmyatt** [comment]
The classes in preprocessing are not scikit-learn compatible [transformers](https://scikit-learn.org/stable/data_transforms.html) since they don't implement `fit` and `transform` as separate methods.

**Comment by rtavenar** [comment]
@GillesVandewiele is there a reason why, in the preprocessing module, some objects have both fit and transform methods even if fit does nothing and others only have fit_transform ?

**Comment by GillesVandewiele** [comment]
I'm not entirely sure, but my tests may skip those classes at this moment (as they do not inherit from `Estimator`).

**Comment by rtavenar** [comment]
This is done for all transformers in preprocessing now. Waiting for Travis, if things pass, I'll close this issue.
