### ISSUE TITLE
Empty return

### ISSUE THREAD

**Issue by LevavasseurYann** [rtavenar/tslearn#49]
I'm trying to use Kmean Kshape and Sax in class methods i've write but whenever thoses three methods are called it return nothing. I am compeled to call this methods directly in the main files.

**Comment by rtavenar** [comment]
Hi,

Could you provide some sample code, because I'm not sure to get what you mean.

**Comment by rtavenar** [comment]
Hi,

You should check the arguments you pass to `TimeSeriesKMeans`'s init and maybe use keyword-style arguments so that you don't mess up with the ordering of the arguments.
