### ISSUE TITLE
`TimeSeriesScalerMeanVariance` got warning of dividing zero when the time series is 0

### ISSUE THREAD

**Issue by DongminWu** [rtavenar/tslearn#52]
Hi, 

Thanks for your brilliant works of building this library!

I am trying to use `tslearn.preprocessing.TimeSeriesScalerMeanVariance` for standardization, but it failed when one of my data samples is pure `0`. Here is the example:

```
t = np.array([[0,0,0],[1,2,3]])
TimeSeriesScalerMeanVariance().fit_transform(t)
```

the output for the above code is:

```
/lib/python3.6/site-packages/tslearn/preprocessing.py:153: RuntimeWarning: invalid value encountered in true_divide
  X_[i, :, d] = (X_[i, :, d] - cur_mean) * self.std_ / cur_std + self.mu_
array([[[        nan],
        [        nan],
        [        nan]],

       [[-1.22474487],
        [ 0.        ],
        [ 1.22474487]]])
```

The issue is the standard deviation of a `[0,0,0]` is 0, it there any good methods for working around?

**Comment by rtavenar** [comment]
Hi and thanks for this bug report.

I guess for this, the best idea would be to take inspiration from `sklearn` (cf [here](https://github.com/scikit-learn/scikit-learn/blob/a24c8b464d094d2c468a16ea9f8bf8d42d949f84/sklearn/preprocessing/data.py#L61))

This means setting variance to 1. (arbitrarily) as soon as it is zero.

I'll try to do it asap. Do not hesitate to propose a PR on this if you have time before I do :)

**Comment by rtavenar** [comment]
OK, It was pretty straight-forward, so I fixed it directly.

The bug should not exist anymore starting from version `tslearn-0.1.18.4`

**Comment by GillesVandewiele** [comment]
Just when I was about to contribute a bit!! You're too fast @rtavenar ..

I ported the code to numpy though, I expect it to be faster.

```
X_ = to_time_series_dataset(X)
means, stds = np.mean(X_, axis=1), np.std(X_, axis=1)
stds[stds == 0] = 1
return (X_ - means) * self.std_ / stds + self.mu_
```

**Comment by GillesVandewiele** [comment]
Here's a few stats:

`TimeSeriesScalerMeanVariance(mu=0., std=1.).fit_transform([np.random.rand(10000000)])` takes 0.6294596195220947 seconds for the numpy implementation and  0.646794319152832 with the original implementation. 

For vectors of length 100000000 the numpy implementation is even slower... Strange stuff...

**Comment by DongminWu** [comment]
tks for such a fast fixing
