### ISSUE TITLE
Distance function choice for DTW

### ISSUE THREAD

**Issue by dmitra79** [rtavenar/tslearn#54]
I've been looking at different DTW implementations (ex.  via DTW R package, fastdtw, UCR Suite) and came upon this package. I have some questions/suggestions:
- The documentations (http://tslearn.readthedocs.io/en/latest/gen_modules/tslearn.metrics.html) doesn't seem to specify what actual distance function is used in DTW (ex. Manhattan, Euclidean, etc)
- I tried looking through the code, found usage of sqeuclidean from scipy.spatial.distance - but am unable to get the same results as other packages produce with this distance. Are additional transformations applied? It would be good to have a sample result on a small piece of data.
- Since scipy distances appear to be used, why not make that a parameter that user can select for dtw?

**Comment by dmitra79** [comment]
After playing more with the dtw and looking in the code,  I realize the cause of my confusion re distance function: sqeuclidean is used compute the local distances, but then a square root is applied to the final cost to make the function more like Euclidean distance along the path. This is unlike other packages, where the final distance is the sum of distances along the path without additional transformations. It would be great if this was documented.

**Comment by rtavenar** [comment]
Hi,

Thanks for your valuable feedback. This should now be fixed in the doc of `dtw`, `dtw_path` and `cdist_dtw` (should appear on ReadTheDocs in a few minutes).

**Comment by thusithathilina** [comment]
Shouldn't distance matric is just the absolute distance rather than the Euclidean or sqeuclidean?
