### ISSUE TITLE
Is there a way to parallelise the algorithms?

### ISSUE THREAD

**Issue by tolgamalachi** [rtavenar/tslearn#55]
Hello guys,

first of all thanks for this great project!
Right now i am heavily using the k-Shape-Algorithm for clustering (imho) huge amounts of data.
n = 5.000.000, k = 6;8;10;12, m = 56
O(max{n·k ·m· log(m), n·m2, k ·m3}) (complexity of k-Shape from the original paper)

And this takes about 150hours on an Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz. Sadly the algorithm only uses one core. How can we fix this? How can we make this faster? I am quite new to Python but maybe you have an idea?

Thanks in advance =)

**Comment by GillesVandewiele** [comment]
Hello, I do not really know the k-shape algorithm, but I would try to parallelize the following methods:

`_update_centroids`: https://github.com/rtavenar/tslearn/blob/master/tslearn/clustering.py#L694

AND

`_assign`: https://github.com/rtavenar/tslearn/blob/master/tslearn/clustering.py#L704

But this would require you to also move away from the current numpy code, so I cannot ensure that it would actually work much faster...

**Comment by jlc-christie** [comment]
@tolgamalachi might be worth installing numba and seeing if you can wrap the methods @GillesVandewiele in the `@jit` decorator, e.g. `@jit(nopython=True, parallel=True)`.

Doesn't always work well but if the function is simple enough it often produces good optimizations with almost no effort. However, the parallel=True argument is an experimental feature according to numba so you might have to look in to the implications of that.

**Comment by andmib** [comment]
Has anybody tried wrapping `TimeSeriesKMeans` with `@jit`? Was it successfully? I'd also like to find a way to speed up extremely large `n` datasets; particularly when doing dynamic time warping, it takes a lot of computation time but is only utilizing a single core.

**Comment by choltz95** [comment]
Also requesting parallel DTW & GAK

**Comment by GillesVandewiele** [comment]
As far as I know, DTW and GAK are stateless, you provide it with two timeseries and you get a similarity score returned. Most often, you want to construct a pairwise distance matrix, for which the calculation can easily be parallellized using `multiprocessing` from Python. You can divide your matrix in blocks and let each process calculate its own block.

**Comment by choltz95** [comment]
Yes - it would be great to integrate multiprocessing into the cdist_dtw/cdist_gak computation.

**Comment by rtavenar** [comment]
That would probably make sense, indeed. Could anyone tell me what it would imply in terms of additional code/ maintainability/ additional dependencies?

**Comment by rtavenar** [comment]
> Also requesting parallel DTW & GAK

Can anyone tell if that fits well with the latest (faster) numba implementation? 

By the way, if you want a faster dtw/gak implementation, you should check the dev branch of tslearn (or future 0.2 version) since @johannfaouzi did a great job on making dtw computations faster.

**Comment by johannfaouzi** [comment]
Regarding DTW, at a glance I would say that only the computation of the cost matrix can be parallelized (the accumulated cost matrix and the path require dynamic programming), and that it could be helpful to have a function for univariate time series (calling numpy.linalg.norm is probably inefficient, although I did not run any comparison to prove it).

As Gilles mentioned it, when dealing with a lot of time series, each DTW score can be computed using parallelization. Joblib has been vendored from scikit-learn, so it could be a good idea to use the same API as scikit-learn (n_jobs and using joblib).

**Comment by rtavenar** [comment]
> Regarding DTW, at a glance I would say that only the computation of the cost matrix can be parallelized (the accumulated cost matrix and the path require dynamic programming), and that it could be helpful to have a function for univariate time series (calling numpy.linalg.norm is probably inefficient, although I did not run any comparison to prove it).

yep, I changed it in latest versions of dev and that helps a lot, indeed.


> As Gilles mentioned it, when dealing with a lot of time series, each DTW score can be computed using parallelization. Joblib has been vendored from scikit-learn, so it could be a good idea to use the same API as scikit-learn (n_jobs and using joblib).

Ok, I could try to have a look, or if anyone would like to work on it, I would be happy to help.

**Comment by rtavenar** [comment]
@johannfaouzi : I just started a new PR for the parallel computations in `cdist_dtw` using `joblib` (not tested on large problems with multiple cores). Any feedback would be more than welcome.

**Comment by rtavenar** [comment]
The PR has been merged: starting from tslearn v0.2 (to be released very soon), `cdist_dtw`, `cdist_gak` as well as all estimators relying on those cross-distance computations have a `n_jobs` attribute that can allow parallel computations.

**Comment by thusithathilina** [comment]
@rtavenar Do we have a sample for this? I do have a large dataset that contains about 48D, 150000 time-series. I can give a try.

**Comment by GillesVandewiele** [comment]
Hi @thusithathilina, it should be as easy as specifying the `n_jobs` parameter to the estimator.
