### ISSUE TITLE
Silhouette score with euclidean metric does not work

### ISSUE THREAD

**Issue by ColinLeverger** [rtavenar/tslearn#61]
Hello,

I am playing with the silhouette score and realised it does not work with the euclidean metric.

Simple steps to reproduce the bug I encounter now:

```
>>> from tslearn.generators import random_walks
>>> from tslearn.metrics import cdist_dtw
>>> X = random_walks(n_ts=50, sz=32, d=1)
>>> labels = numpy.random.randint(2, size=50)
>>> s_sc = silhouette_score(X, labels, metric="euclidean")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/tslearn/clustering.py", line 142, in silhouette_score
    sklearn_X = cdist(X, X, metric="euclidean")
  File "/usr/lib64/python3.6/site-packages/scipy/spatial/distance.py", line 2590, in cdist
    raise ValueError('XA must be a 2-dimensional array.')
ValueError: XA must be a 2-dimensional array.
```

Some interesting links I found documenting this problem (which comes from sklearn if I am correct):
- http://comments.gmane.org/gmane.comp.python.scientific.user/29106 and http://comments.gmane.org/gmane.comp.python.scientific.user/29106 with some explanations
- https://stackoverflow.com/questions/13773537/python-cdist-error-valueerror-xa-must-be-a-2-dimensional-array

Do not know how to help, though. We probably have to work on the lines 141-142 of ```clustering.py``` file.

**Comment by rtavenar** [comment]
Hi Colin,

Should be fixed in v.0.1.19.1 (added a doctest for it). Let me know if this is not enough.

**Comment by ColinLeverger** [comment]
Fixed! Thanks Romain for the fast reply :)
