### ISSUE TITLE
I want a method to evaluate the performance.

### ISSUE THREAD

**Issue by KarenPHS** [rtavenar/tslearn#66]
Hello everyone, the package is good to deal with time series clustering. But every time I'm confused about how to set clusters. So, I want some methods to evaluate the performance, like Calinski-Harabaz Index and Silhouette Coefficient. Thank you.

**Comment by GillesVandewiele** [comment]
tslearn has  a custom [silhouette_score](https://tslearn.readthedocs.io/en/latest/gen_modules/clustering/tslearn.clustering.silhouette_score.html?highlight=silhouette).

You could maybe also calculate the resulting cluster for each of your time series (`cluster_centers_` attribute) and then use sklearn metrics.

**Comment by rtavenar** [comment]
I'm closing this, assuming @GillesVandewiele 's answer covered at least part of the question. Please re-open if necessary.
