### ISSUE TITLE
Reproduce shapelets

### ISSUE THREAD

**Issue by humaun21** [rtavenar/tslearn#67]
I want to reproduce same results(Shapelets) from same data. I didn't find anything like(Shuffle=  false, or random state). What parameter do I need to change because each time i run the model on same data and it produces another set of result.

What do I need to change here?
# Set the number of shapelets per size as done in the original paper
shapelet_sizes = grabocka_params_to_shapelet_size_dict(n_ts=X_train.shape[0],
                                                       ts_sz=X_train.shape[1],
                                                       n_classes=len(set(y_train)),
                                                       l=0.1,
                                                       r=2)

# Define the model using parameters provided by the authors (except that we use fewer iterations here)
shp_clf = ShapeletModel(n_shapelets_per_size=shapelet_sizes,
                        optimizer=Adagrad(lr=.1),
                        weight_regularizer=.01,
                        max_iter=200,
                        verbose_level=0)
shp_clf.fit(X_train, y_train)

**Comment by rtavenar** [comment]
Hi @humaun21 ,

Thanks for your feedback.

I have tried to implement such a feature in `tslearn-0.1.21`. Could you try to upgrade to this version, add a parameter `random_state=pick_your_integer_value_here` to the constructor of `ShapeletModel` and check that you can achieve reproducibility then?

By the way, I'm pretty sure my hack is not great, so I'm open to any suggestion to improve on that hack.

**Comment by humaun21** [comment]
Hi @rtavenar 
Thanks for your reply.  It's helpful.
Best
Humaun

**Comment by rtavenar** [comment]
I guess that means I can close. Feel free to re-open otherwise.
