### ISSUE TITLE
Is there documentation for the KNeighborsTimeSeries metrics? 

### ISSUE THREAD

**Issue by AstronautFireman** [rtavenar/tslearn#68]
The API Reference states that KNeighborsTimeSeries (and it's classifier) can take a metric from  `{'dtw', 'euclidean', 'sqeuclidean', 'cityblock'}` as well as a dict containing meteric_params. 

'dtw' is pretty straight forward, and this seems to be able to take the 'global_constraint' and 'sakoe_chiba_radius' parameters as keywords, however I don't have much a clue of what 'euclidean', 'squclidean', or 'cityblock' are, nor what parameters (such as radius?) I can pass. 

Also, is there an option for lb_keogh as a metric for KNeighborsTimeSeriesClassifier?

Thanks for this wonderful package!

**Comment by rtavenar** [comment]
Thanks for your feedback.

Doc is now improved on that point. Let us know if that better fits your needs.

Best,
Romain

**Comment by rtavenar** [comment]
I'm closing this, assuming that the question has been answered. Please re-open if necessary.
