### ISSUE TITLE
verbosity levels for TimeSeriesKMeans

### ISSUE THREAD

**Issue by jlc-christie** [rtavenar/tslearn#69]
It would be beneficial to have different levels of verbosity when computing k-means on time series data. Specifically, it would be nice to have some kind of progress indicator, as when computing on large datasets its unclear whether a job is feasible to wait for or not.

**Comment by rtavenar** [comment]
This is now possible -- merged to `dev` branch (will be available in tslearn v0.3 on PyPI) -- thanks to the amazing work by @choltz95 !
