### ISSUE TITLE
can not install module with error "Failed building wheel for tslearn"

### ISSUE THREAD

**Issue by duangrux** [rtavenar/tslearn#74]
My problem is I can not install "tslearn" package on mac with python3.
It show error :  " Failed building wheel for tslearn"

May you provide some solution for install this package?
@rth @rtavenar

**Comment by GillesVandewiele** [comment]
Do you have more stack trace than that single line please?

**Comment by duangrux** [comment]
> Do you have more stack trace than that single line please?
I attach sreencshot in below, i hope you can help me please

![screen shot 2561-10-16 at 09 29 53](https://user-images.githubusercontent.com/43942541/46987275-1cfb6500-d126-11e8-8d41-d09b438be5d0.png)
![screen shot 2561-10-16 at 09 29 59](https://user-images.githubusercontent.com/43942541/46987280-22f14600-d126-11e8-81c2-3206f1b04e65.png)

**Comment by GillesVandewiele** [comment]
Seems to be a problem with xcrun or something like that (second to last line). You'll need to install xcode:

https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path

**Comment by duangrux** [comment]
> Seems to be a problem with xcrun or something like that (second to last line). You'll need to install xcode:
> 
> https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path

It's workkkkk, thank you so much  :)
