### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by alexandrefelipemuller** [rtavenar/tslearn#79]
Hello, 

I'm having some difficulties on tslearn enviroment. I'm trying to execute basic example using tslearn, but I don't know why utils is not recognized as module:

$ python tslearn.py
Traceback (most recent call last):
  File "tslearn.py", line 1, in <module>
    from tslearn.utils import to_time_series
  File "/home/ppginf/afmsouza/shapelet_exemplo/tslearn.py", line 1, in <module>
    from tslearn.utils import to_time_series
ImportError: No module named utils
---
I\'ve both modules installed

> $ pip show utils tslearn
>Name: utils
>Version: 0.9.0
>Summary: Python Distribution Utilities
>Home-page: http://github.com/haaksmash/pyutils
>Author: Haak Saxberg
>Author-email: haak.erling@gmail.com
>License: UNKNOWN
>Location: /nobackup/ppginf/afmsouza/.local/lib/python2.7/site-packages
>Requires: 
>Required-by: 
>---
>Name: tslearn
>Version: 0.1.24
>Summary: A machine learning toolkit dedicated to time-series data
>Home-page: http://tslearn.readthedocs.io/
>Author: Romain Tavenard
>Author-email: romain.tavenard@univ-rennes2.fr
>License: UNKNOWN
>Location: /nobackup/ppginf/afmsouza/.local/lib/python2.7/site-packages
>Requires: scipy, numpy, Cython, scikit-learn
>Required-by: 

maybe tslearn was built without utils module, I'm stuck for 2 weeks in this problem.. do you know what could be the problem?

**Comment by rtavenar** [comment]
Hi, I guess the probloem comes from the fact that your script is named `tslearn.py`, hence python is confused between your script and the `tslearn` package.

**Comment by alexandrefelipemuller** [comment]
I'm afraid it's not.. I move the file to new name but the problem is the same
$ python tsexample.py 
Traceback (most recent call last):
  File "tsexample.py", line 1, in <module>
    from tslearn.utils import to_time_series
  File "/home/ppginf/afmsouza/shapelet_exemplo/tslearn.py", line 1, in <module>
ImportError: No module named utils

I've tried in 2 different stations on my personal PC with Ubuntu and the university terminal using MINT both Im with same state

**Comment by GillesVandewiele** [comment]
Did you delete the other file? There should be NO `tslearn.py` file in that directory

**Comment by alexandrefelipemuller** [comment]
Sure I've moved from tslearn to new name... is there something I can do to increase verbosity of this import process?

**Comment by MarcCoru** [comment]
it seems that in your `/home/ppginf/afmsouza/shapelet_exemplo/tslearn.py` file is still named `tslearn.py` and probably confused with the module, as @rtavenar said. Also `tslearn.utils` refers to the `https://github.com/rtavenar/tslearn/blob/master/tslearn/utils.py`-file and not a separate module.

I also could not reproduce the import issue in a new conda environment (named `tmpenv` in python 3.7.1):
```bash
$conda create -y -n tmpenv pip numpy cython
$conda activate tmpenv
(tmpenv)$pip install tslearn
(tmpenv)$python -c "from tslearn.utils import to_time_series"
```
Can you check if that works for you?

**Comment by alexandrefelipemuller** [comment]
Yes, thats really the issue.... there was a tslearn.pyc file .. maybe it was remnant from tslearn.py somewow.. thanks a lot!
