### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by jen0liu** [rtavenar/tslearn#84]
I'm using tslearn to launch an app on heroku. When installing packages via requirements.txt, it always gave this error message "No module named 'numpy'", corresponding to this line(https://github.com/rtavenar/tslearn/blob/master/setup.py#L2).  I'm able to install numpy first then add tslearn with heroku push. I guess these environments don't have numpy pre-installed so we probably need to handle dependencies differently?

**Comment by rtavenar** [comment]
Hi @jen0liu and thanks for your feedback.

Hum, you're right, it seems like a real issue. I am not an expert (at all) in setups, so if anyone can help on that one, that would be great. 

Is there a way to remove the `numpy` import in `setup.py` while still having the same behaviour?

**Comment by rth** [comment]
Well numpy is a build dependency, so it should be installed in the environment when `setup.py` is run. There is no real a way around it, short of building binary wheels and adding some conditional logic in `setup.py` on whether there package is built from source or not, but we are not there.

Overall it feels more like an issue with `heroku` configuration, rather than a bug in tslearn.

**Comment by rtavenar** [comment]
So, @rth , if I understand you well, the way we deal with the `numpy` dependency in `setup.py` is OK? What do you think about the related discussion about `cython` in #132 ?

**Comment by rth** [comment]
Well there are two choices,
 - say that numpy (and Cython when building from sources) needs to be explicitly installed before installing tslearn (and fail if it's not present). This is what scikit-learn is [currently doing](https://github.com/scikit-learn/scikit-learn/blob/c4f372c2de33db77e4dbc5a136d1443a20a3cb45/setup.py#L278). 
 - Import numpy and scipy in a custom build_ext class as suggested in that other issue https://github.com/LeeKamentsky/python-javabridge/pull/131/files#diff-2eeaed663bd0d25b7e608891384b7298 . Though this whole part is non trivial and a bit hacky https://github.com/scikit-learn/scikit-learn/issues/7867#issuecomment-261488725. The real solution for this is [PEP 518](https://www.python.org/dev/peps/pep-0518/) with defining build dependencies in `pyproject.toml`, but it's not fully adopted in scientific python packages yet.

So overall, there may be ways to make this smoother but it's not that straightforward and anyway saying that numpy, cython need to be installed when building from sources is not a huge constraint I think. The fact that most people on windows won't have a working compiler by default, is a bigger concern IMO.

https://github.com/rtavenar/tslearn/issues/150 would be another way to address this.

**Comment by rtavenar** [comment]
OK, so what I can do at the moment is to make it clearer in the docs that `numpy`, `Cython` and C++ build tools are required to build from PyPI / github.

And we should use #150 to discuss what we can do to deliver wheels for more platforms.

Thanks @rth for the help!
