### ISSUE TITLE
Multivariate Time Series

### ISSUE THREAD

**Issue by sknepal** [rtavenar/tslearn#87]
Hi,

I couldn't find any information in the documentation regarding support for multivariate time series.

I have a dataset like this:

feature 1 | feature 2 | ... | feature n | label 
-- | -- | -- | -- | -- 
23.4 | 12.5 | ... | 1.34 | Class 1 
27.3 | 14.7 | ... | 2.46 | Class 1 
... | ... | ... | ... | Class 2 
26.5 | 11.2 | ... | 2.32 | Class 2

where N rows of data belongs to one subject (ie there's another dimension which identifies the subject that the time series data belongs to). I was looking to try knn with dtw for classification. Does tslearn dtw implementation support multivariate time series? Or better yet, are there any implementations in the library that *don't* support multivariate time series. Thank you!

Edit: On  a related note, how do you load multivariate time series at all? was just going through #2 ..it is actually pretty easy to load multivariate dataset into tsfresh but the process seems to be undocumented/not clear in tslearn. I am not sure how to load multivariate dataset using pandas. Can you please help?

**Comment by Simon0494** [comment]
> Does tslearn dtw implementation support multivariate time series?
Yes, they do, but only on a limited base, eg. they support DTW of multidimensional time series.

`seq1 = [0, 0, 2, 4, 6, 4, 2, 0, 0]
seq2 = [3, 3, 2, 4, 5, 6, 1, 2, 1]
ts = to_time_series([seq1,seq2])
`

I don't know if you directly convert a pandas dataframe into a multi dimensional dataframe but u can do it by yourself (see above).

**Comment by rtavenar** [comment]
You could also have a look at [that page](https://tslearn.readthedocs.io/en/latest/variablelength.html) in the docs.
