### ISSUE TITLE
1D-SAX default 'sigma_l'

### ISSUE THREAD

**Issue by StevenElsworth** [rtavenar/tslearn#89]
I implemented my own version of 1D-SAX and tested it against tslearn version. I believe the default sigma for slope Gaussian breakpoints may be wrong. I believe the paper recommends a variance of 0.03/L where L is the length of each segment. 
https://link.springer.com/content/pdf/10.1007%2F978-3-642-41398-8.pdf

This implementation uses a variance of 0.03/L where L is the length of the original time series.

**Comment by rtavenar** [comment]
Dear @StevenElsworth 

Thanks for pointing this. You are perfectly right. Would you like to produce a PR for that or shall I do it?

Romain

**Comment by StevenElsworth** [comment]
Dear @rtavenar 

I don't mind either way.  For ease, I guess you can produce a PR.

Thanks, 
Steven

**Comment by rtavenar** [comment]
Well, I would say that if you feel you can do it, you should, as you were the one finding the bug. But if you want me to do so, I can also. If you haven't done so by the end of the week, I will.

Thanks again!

**Comment by StevenElsworth** [comment]
Well I have never done it before. I guess I should learn. I see the Issue is still open and no pull request has been made so I will do this today. Thanks.

**Comment by rtavenar** [comment]
This is fixed from version 0.1.29
