### ISSUE TITLE
Preprocessors should not inherit from TransformerMixin

### ISSUE THREAD

**Issue by jamesmyatt** [rtavenar/tslearn#91]
The purpose of the `TransformerMixin` class in scikit-learn is to provide the `fit_transform` method when you already have `fit` and `transform` methods. It is a [mixin](https://en.wikipedia.org/wiki/Mixin) class not an [interface](https://en.wikipedia.org/wiki/Protocol_(object-oriented_programming)) or [abstract](https://en.wikipedia.org/wiki/Abstract_type) class. Hence, if you're not implementing `fit` and `transform` separately, your preprocessors should not inherit from it. In fact, if you implement the `fit_transform` method then there's no reason to inherit from it since you have overriden all of the methods that it provides.

I think this is the origin of the confusion about the function of the preprocessors, e.g.  in #48 and #56.

Also, `TimeSeriesResampler` is not scikit-learn compliant because it changes the number of observations.

**Comment by rtavenar** [comment]
Closed since the discussion happens in  #48 

Also, TimeSeriesResampler does not change the number of observations, but the shape of each observation.
