### ISSUE TITLE
Multiple Observations Per Datapoint

### ISSUE THREAD

**Issue by rshtirmer** [rtavenar/tslearn#93]
I have a quick question, hopefully this is the right place. 
So if I have a dataset with 3 TS "objects" with one observation at each T, I can use the following:
`X = to_time_series_dataset([[1, 2, 3, 4], [1, 2, 3], [2, 5, 6, 7, 8, 9]])
`
But say I had 2+ observations at each T for example, would TSLearn support that?
Essentially a dataset like this:
`X = to_time_series_dataset([[{1,3}, {2,1}, {3,5}], [{1,2}, {2,3}, {4,2}], [{2,4}, {1,4}, {2,2}]])
` 

Thanks!

**Comment by rtavenar** [comment]
Hi @rshtirmer 

That matches the multivariate time series standard, no? If so, 3rd axis in tslearn data arrays is here for that.
