### ISSUE TITLE
How do you calculate the local distance for multi-dimentional time series data with DTW?

### ISSUE THREAD

**Issue by Arsener** [rtavenar/tslearn#98]
In the API reference of tslearn.metric.dtw, you said "Compute Dynamic Time Warping (DTW) similarity measure between (possibly **multidimensional**) time series and return it.". So I want to kown if you used the Euclidean distance to calculate the local distance for multi-dimentional time series data. If not, how did you calculate the local distance?

**Comment by rtavenar** [comment]
Hi @Arsener 

Thanks for your interest in tslearn. As shown here: https://github.com/rtavenar/tslearn/blob/master/tslearn/cydtw.pyx#L80 the local distance is the euclidean one (more precisely, dtw is computed as the squared root of the sum of squared euclidean distances along the optimal path). 

The dtw doc should be fixed to make things clearer,  will do it as soon as I can.

**Comment by Arsener** [comment]
Thanks for your reply.
